#!/usr/bin/env python3

"""
step_3_mageck_test.py

Iterates over specified treatments and controls in config.py, gathers matching 
columns from the count table, and writes a batch script to run MAGeCK test. 
Finally, submits the job to the cluster via bsub.

Usage:
    python3 mageck_test.py

Requires:
-   Python environment with pandas, conda, etc., installed
-   Count table: a tab-delimited file with a header row, in the same layout 
    as the one generated by step_1_processAmplicons.R

"""

import os
import time
import subprocess
import re
import config

### Set working directory
project_name = config.PROJECT_NAME
analysis_dir = config.ANALYSIS_DATA
importable_dir = config.IMPORTABLE_DATA

# Set up label based on number of allowed mismatches
if config.ALLOW_MISMATCHES and config.TARGET_MISMATCHES == 2:
    MISMATCH_STATUS = "twoMismatches"
elif config.ALLOW_MISMATCHES and config.TARGET_MISMATCHES == 1:
    MISMATCH_STATUS = "oneMismatch"
else:
    MISMATCH_STATUS = "noMismatches"

# Set path to count table
counts = f"{project_name}_counts_{MISMATCH_STATUS}_mageck.txt"
count_table = os.path.join(importable_dir, counts)

# Directory for storing output and logs
work_dir = os.path.join(analysis_dir, "mageck")
# LSF job name
job_name = f"{project_name}.magecktest"
# Log directory
log_dir = os.path.join(work_dir, "log")

# LSF log files
log_out_file = os.path.join(log_dir, f"{project_name}.out")
log_err_file = os.path.join(log_dir, f"{project_name}.error")
batch_file = os.path.join(log_dir, f"{project_name}.batch")


def main():
    # Create output directories
    os.makedirs(work_dir, exist_ok=True)
    os.makedirs(log_dir, exist_ok=True)

    # Build initial batch script
    batch_cmd = f"""\
#!/bin/bash
#BSUB -P {project_name}
#BSUB -J {job_name}
#BSUB -o {log_out_file}
#BSUB -e {log_err_file}
#BSUB -q normal
#BSUB -n 8,32  # number of cores to request
#BSUB -M 64400
#BSUB -R "rusage [mem=64400] span[hosts=1]"    # Reserve the different CPU cores under the same node


# Load python environment with mageck
conda activate crisprscreen


"""

    # Read first line (header) from count table
    with open(count_table, "r", encoding="utf-8") as f:
        header_line = f.readline().rstrip("\n")

    header_cols = header_line.split("\t")

    # For each treat vs control combination
    for treat in config.TREATMENTS:
        for ctrl in config.CONTROLS:
            if treat.lower() == ctrl.lower():
                continue  # skip identical

            # Collect columns that match 'treat' ignoring any in config.EXCLUDE_SAMPLES
            treat_cols = [
                col for col in header_cols
                if re.search(treat, col, re.IGNORECASE)
                and not any(re.search(excl, col, re.IGNORECASE) for excl in config.EXCLUDE_SAMPLES)
            ]
            # remove trailing _column\d+ if it exists
            treat_cols = [re.sub(r"_column\d+", "", c) for c in treat_cols]

            # Collect columns that match 'ctrl'
            control_cols = [
                col for col in header_cols
                if re.search(ctrl, col, re.IGNORECASE)
                and not any(re.search(excl, col, re.IGNORECASE) for excl in config.EXCLUDE_SAMPLES)
            ]
            control_cols = [re.sub(r"_column\d+", "", c) for c in control_cols]

            # Define output name (treat_vs_control)
            output = f"{treat}_vs_{ctrl}"
            output_dir = os.path.join(work_dir, output)
            os.makedirs(output_dir, exist_ok=True)

            # Join columns with commas for mageck
            t = ",".join(treat_cols)
            c = ",".join(control_cols)

            # Build mageck test command
            cmd = f"""
# Run Mageck test for {treat} vs {ctrl}
mageck test -k {count_table} -n {output} --norm-method median --adjust-method fdr -c {c} -t {t}
mv {output}* {output_dir}
"""

            batch_cmd += cmd

    # Write out the batch script
    with open(batch_file, "w", encoding="utf-8") as bf:
        bf.write(batch_cmd)

    # Submit the job
    submit_cmd = f"bsub < {batch_file} -J {job_name}"
    print(submit_cmd)
    subprocess.run(submit_cmd, shell=True)

    time.sleep(1)

if __name__ == "__main__":
    main()
